# Generated by Django 5.2.7 on 2025-11-11 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('puntos_lealtad', models.IntegerField(default=0)),
                ('tipo_entrenador', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('estado_pedido', models.CharField(choices=[('P', 'Pendiente'), ('E', 'Enviado'), ('T', 'Entregado')], default='P', max_length=50)),
                ('total_monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('codigo_rastreo', models.CharField(blank=True, max_length=100)),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('es_pago_verificado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='app_Pokemon.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_comprada', models.IntegerField(default=1)),
                ('categoria', models.CharField(max_length=50)),
                ('generacion', models.IntegerField(default=1)),
                ('es_legendario', models.BooleanField(default=False)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_en_pedido', to='app_Pokemon.pedido')),
            ],
        ),
    ]
