# Generated by Django 5.2.7 on 2025-11-13 15:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Pokemon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetExpansion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_set', models.CharField(default='Nuevo Set', max_length=150, unique=True)),
                ('abreviatura', models.CharField(default='SET', max_length=10, unique=True)),
                ('fecha_lanzamiento', models.DateField(auto_now_add=True)),
                ('num_cartas_total', models.IntegerField(default=0)),
                ('es_reciente', models.BooleanField(default=True)),
                ('simbolo_set', models.CharField(default='★', max_length=10)),
                ('idioma', models.CharField(default='Español', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cantidad_comprada',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='pedido',
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_entrenador',
            field=models.CharField(default='Entrenador', max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigo_rastreo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(default='Efectivo', max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='Descripción del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(default='Producto Pokemon', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='DetalleProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('es_item_digital', models.BooleanField(default=False)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('observacion_item', models.TextField(blank=True, default='')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app_Pokemon.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='app_Pokemon.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carta', models.CharField(default='Nueva Carta', max_length=150)),
                ('num_carta_en_set', models.CharField(default='001/000', max_length=10)),
                ('tipo_pokemon', models.CharField(default='Normal', max_length=50)),
                ('rareza', models.CharField(default='Común', max_length=50)),
                ('es_holo', models.BooleanField(default=False)),
                ('condicion_carta', models.CharField(choices=[('NM', 'Near Mint'), ('LP', 'Lightly Played'), ('MP', 'Moderately Played'), ('HP', 'Heavily Played')], default='NM', max_length=50)),
                ('valor_mercado_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('set_expansion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartas', to='app_Pokemon.setexpansion')),
            ],
        ),
    ]
